# Generated by Django 3.1.4 on 2020-12-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.PositiveIntegerField(verbose_name='Опыт работы')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
            ],
        ),
    ]
