# Generated by Django 3.1.4 on 2020-12-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OII_LR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='age',
            field=models.FloatField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='experience',
            field=models.FloatField(verbose_name='Опыт работы'),
        ),
    ]
