# Generated by Django 3.1.4 on 2020-12-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OII_LR', '0002_auto_20201207_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='age_bit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='age_middle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='age_small',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='experience_big',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='experience_middle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='experience_small',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
