# Generated by Django 3.1.4 on 2020-12-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OII_LR', '0004_auto_20201207_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='first_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='last_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
